---
# title: 

output: github_document
fig_caption: yes


---

\ 

This is Appendix B from the manuscript "Domains of scale in cumulative effects of energy sector development on boreal birds" by @Crosby. submitted to the journal *Landscape Ecology*. The objective of this document is to describe, and demonstrate how to run, the scale integrated occupancy model using Bayesian lasso for variable selection. 

### Software requirements:  

* R for downloading and processing data, and running the models [@RCoreTeam2017], downloadable from https://www.r-project.org/  

* JAGS for estimating model parameters using Markov chain Monte Carlo (MCMC) through the use of a Gibbs sampler [@Plummer2013], downloadable from https://mcmc-jags.sourceforge.io/  

* R extension packages: **tidyverse**, **jagsUI**, and **loo**. These can be installed from R using the "install.packages" function  


### Files:  

* **big-grid-data.Rdata**: Post-processed data used to fit the models in this analysis 

  - These data can be downloaded from the Github repository at: [big-grid-data.Rdata](https://github.com/crosbya1/multi-level-occupancy/blob/main/docs/big-grid-data.Rdata)

To be consistent with the [GitHub repository](https://github.com/crosbya1/multi-level-occupancy), when following this tutorial in R, create a directory named "docs" within your R working directory to store the data in. 

